blog/urls.py
from django.urls import path

from blog.views import PostCreateView, PostListView, PostDetailView, PostDeleteView, PostUpdateView

app_name = 'blog'
# from blog.views import PostListView

urlpatterns = [
    path('', PostListView.as_view(), name='post_list'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from newsletter.views import ContactsTemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('contacts/', ContactsTemplateView.as_view(), name='contacts'),
    path('', include('newsletter.urls', namespace='newsletter')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newsletter/urls.py
from django.urls import path


from newsletter.views import NewsletterListView, NewsletterDetailView, NewsletterCreateView, NewsletterUpdateView, \
    NewsletterDeleteView, ClientCreateView, ClientDetailView, ClientUpdateView, ClientDeleteView, MessageDetailView, \
    MessageCreateView, MessageUpdateView, MessageDeleteView, ClientListView, MessageListView, AttemptListView, \
    NewsletterFinishView

app_name = 'newsletter'



urlpatterns = [
    # Newsletter
    path('', NewsletterListView.as_view(), name='newsletter_list'),
    path('newsletter/<int:pk>', NewsletterDetailView.as_view(), name='newsletter_page'),
    path('newsletter_create/', NewsletterCreateView.as_view(), name='create_newsletter'),
    path('newsletter_update/<int:pk>', NewsletterUpdateView.as_view(), name='update_newsletter'),
    path('newsletter_delete/<int:pk>', NewsletterDeleteView.as_view(), name='delete_newsletter'),
    # Clients
    path('clients/', ClientListView.as_view(), name='client_list'),
    path('client/<int:pk>', ClientDetailView.as_view(), name='client_page'),
    path('client_create/', ClientCreateView.as_view(), name='create_client'),
    path('client_update/<int:pk>', ClientUpdateView.as_view(), name='update_client'),
    path('client_delete/<int:pk>', ClientDeleteView.as_view(), name='delete_client'),
    # Messages
    path('messages/', MessageListView.as_view(), name='message_list'),
    path('message/<int:pk>', MessageDetailView.as_view(), name='message_page'),
    path('message_create/', MessageCreateView.as_view(), name='create_message'),
    path('message_update/<int:pk>', MessageUpdateView.as_view(), name='update_message'),
    path('message_delete/<int:pk>', MessageDeleteView.as_view(), name='delete_message'),
    # Other
    path('attempts/', AttemptListView.as_view(), name='attempt_list'),
    path('newsletter_finish/<int:pk>/', NewsletterFinishView.as_view(), name='newsletter_finish'),

]

newsletter/models.py
import logging
import pytz
from django.db import models
from django.utils import timezone
from django_apscheduler.models import DjangoJob

from users.models import User
from .scheduler import send_newsletter, scheduler

logger = logging.getLogger(__name__)

NULLABLE = {'null': True, 'blank': True}


class Client(models.Model):
    email = models.EmailField(verbose_name='почта')
    full_name = models.CharField(max_length=50, **NULLABLE, verbose_name='имя')
    comment = models.TextField(verbose_name='комментарий')
    user = models.ForeignKey(User, verbose_name='создатель', blank=True, null=True, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'клиент'
        verbose_name_plural = 'клиенты'

    def __str__(self):
        return self.email


class Message(models.Model):
    topic = models.CharField(max_length=50, verbose_name='заголовок')
    content = models.TextField(verbose_name='текст')
    user = models.ForeignKey(User, verbose_name='создатель', blank=True, null=True, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'сообщение'
        verbose_name_plural = 'сообщения'

    def __str__(self):
        return self.topic


class Newsletter(models.Model):
    STATUS = [
        ('S', 'Successful'),
        ('P', 'In Process'),
        ('F', 'Failed'),
    ]
    FREQ_OPTIONS = [
        ('D', 'Daily'),
        ('W', 'Weekly'),
        ('M', 'Monthly'),
    ]
    initial = models.DateTimeField(verbose_name='начало рассылки')
    end_date = models.DateTimeField(verbose_name='конец рассылки', **NULLABLE)
    finished = models.BooleanField(default=False, verbose_name='завершено')
    frequency = models.CharField(max_length=2, choices=FREQ_OPTIONS, default='W', verbose_name='частота рассылки')
    status = models.CharField(max_length=2, choices=STATUS, default='P', verbose_name='статус')
    message = models.ForeignKey(Message, on_delete=models.CASCADE, verbose_name='сообщение')
    clients = models.ManyToManyField(Client, verbose_name='клиенты')
    user = models.ForeignKey(User, verbose_name='создатель', blank=True, null=True, on_delete=models.CASCADE)


    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.status == 'P':
            job_id = f'send-newsletter-{self.id}'
            logger.info(f"Scheduling job {job_id} for {self.initial}")

            try:
                existing_job = DjangoJob.objects.get(id=job_id)
                scheduler.remove_job(job_id)
                existing_job.delete()
                logger.info(f"Removed existing job {job_id}")
            except DjangoJob.DoesNotExist:
                pass

            scheduler.add_job(
                send_newsletter,
                trigger='date',
                run_date=self.initial.astimezone(pytz.UTC),
                args=[self.id],
                id=job_id,
                replace_existing=True
            )
            logger.info(f"Scheduled new job {job_id} to run at {self.initial.astimezone(pytz.UTC)}")

    def is_active(self):
        now = timezone.now()
        return self.initial <= now <= self.end_date and not self.finished

    class Meta:
        verbose_name = 'рассылка'              
        verbose_name_plural = 'рассылки'
        permissions = [
            (
                'can_view_any_newsletter',
                'can_view_any_newsletter'
            ),
            (
                'can_turn_the_newsletter_off',
                'can_turn_the_newsletter_off'
            )
        ]

    def __str__(self):
        return (f'From {str(self.initial)[:-9]}'
                f' to {str(self.end_date)[:-9]}') if self.end_date else f'From {str(self.initial)[:-9]}'


class Attempt(models.Model):
    STATUS = [
        ('S', 'Successful'),
        ('P', 'In Process'),
        ('F', 'Failed'),
    ]
    newsletter = models.ForeignKey(Newsletter, on_delete=models.CASCADE, null=True)
    client = models.ForeignKey(Client, on_delete=models.CASCADE, null=True)
    message = models.ForeignKey(Message, on_delete=models.CASCADE, null=True)
    last_attempt_time = models.DateTimeField()
    last_attempt_status = models.CharField(max_length=2, choices=STATUS, default='S')
    server_response = models.IntegerField(default=200)

    class Meta:
        verbose_name = 'попытка'
        verbose_name_plural = 'попытки'

    def __str__(self):
        return f"{self.newsletter} to {self.client} at {self.last_attempt_time} - {self.last_attempt_status}"

newsletter/forms.py
from django import forms
from newsletter.models import Newsletter, Client, Message
from django.utils import timezone


class FormStyleMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, forms.BooleanField):
                field.widget.attrs['class'] = 'form-control-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class NewsletterForm(FormStyleMixin, forms.ModelForm):
    initial = forms.DateTimeField(
        widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        input_formats=['%Y-%m-%dT%H:%M'],
    )

    class Meta:
        model = Newsletter
        exclude = ('status', 'user', )

        widgets = {
            'initial': forms.DateTimeInput(attrs={
                'type': 'datetime-local',
                'class': 'form-control'
            }),
            'end_date': forms.DateTimeInput(attrs={
                'type': 'datetime-local',
                'class': 'form-control'
            }),
            'frequency': forms.Select(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')],
                                      attrs={'class': 'form-control'}),
            'message': forms.Select(attrs={'class': 'form-control'}),
            'clients': forms.SelectMultiple(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super().__init__(*args, **kwargs)
        self.fields['clients'].queryset = Client.objects.filter(user=user)
        self.fields['message'].queryset = Message.objects.filter(user=user)


class ClientForm(FormStyleMixin, forms.ModelForm):
    class Meta:
        model = Client
        exclude = ('user', )

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)


class MessageForm(FormStyleMixin, forms.ModelForm):
    class Meta:
        model = Message
        exclude = ('user', )

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)


class NewsletterFinishForm(forms.ModelForm):
    class Meta:
        model = Newsletter
        fields = ['finished']

newsletter/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.exceptions import PermissionDenied
import random
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import ListView, DetailView, TemplateView, CreateView, UpdateView, DeleteView

from blog.models import Post
from newsletter.forms import NewsletterForm, ClientForm, MessageForm, NewsletterFinishForm
from newsletter.models import Newsletter, Client, Message, Attempt
import logging
from newsletter.services import get_newsletters_from_cache

logger = logging.getLogger(__name__)


class UserIsOwnerOrHasPermissionMixin:
    permission_required = None

    def test_func(self):
        obj = self.get_object()
        user = self.request.user
        if user == obj.user or user.has_perm(self.permission_required):
            return True
        return False

    def handle_no_permission(self):
        raise PermissionDenied("You do not have permission to perform this action.")


class ContactsTemplateView(LoginRequiredMixin, TemplateView):
    model = Newsletter
    template_name = 'newsletter/contacts.html'


# Newsletter


class NewsletterListView(ListView):
    model = Newsletter
    template_name = 'newsletter/main_page.html'
    context_object_name = 'newsletters'

    def get_queryset(self):
        return get_newsletters_from_cache()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        now = timezone.now()

        total_newsletters = Newsletter.objects.count()

        active_newsletters = Newsletter.objects.filter(
            initial__lte=now,
            end_date__gte=now,
            finished=False
        ).count()

        unique_clients = Client.objects.distinct().count()

        all_posts = list(Post.objects.all())
        random_posts = random.sample(all_posts, min(len(all_posts), 3))

        context.update({
            'total_newsletters': total_newsletters,
            'active_newsletters': active_newsletters,
            'unique_clients': unique_clients,
            'random_posts': random_posts
        })

        return context


class NewsletterCreateView(LoginRequiredMixin, CreateView):
    model = Newsletter
    form_class = NewsletterForm
    template_name = 'newsletter/newsletter_form.html'
    success_url = reverse_lazy('newsletter:newsletter_list')

    def form_valid(self, form):
        newsletter = form.save()
        user = self.request.user
        newsletter.user = user
        newsletter.save()
        return super().form_valid(form)

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['clients'].queryset = Client.objects.filter(user=self.request.user)
        form.fields['message'].queryset = Message.objects.filter(user=self.request.user)
        return form

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class NewsletterDetailView(LoginRequiredMixin, UserIsOwnerOrHasPermissionMixin, DetailView):
    model = Newsletter
    permission_required = 'newsletter.can_view_any_newsletter'
    template_name = 'newsletter/newsletter.html'

    def get(self, request, *args, **kwargs):
        if not self.test_func():
            return self.handle_no_permission()
        return super().get(request, *args, **kwargs)


class NewsletterUpdateView(LoginRequiredMixin, UserIsOwnerOrHasPermissionMixin, UpdateView):
    model = Newsletter
    form_class = NewsletterForm
    permission_required = 'newsletter.update_newsletter'
    template_name = 'newsletter/newsletter_form.html'
    success_url = reverse_lazy('newsletter:newsletter_list')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class NewsletterDeleteView(LoginRequiredMixin, UserIsOwnerOrHasPermissionMixin, DeleteView):
    model = Newsletter
    permission_required = 'newsletter.delete_newsletter'
    success_url = reverse_lazy('newsletter:newsletter_list')

    def delete(self, request, *args, **kwargs):
        if not self.test_func():
            return self.handle_no_permission()
        return super().delete(request, *args, **kwargs)


# Client


class ClientListView(ListView):
    model = Client
    template_name = 'newsletter/client_list.html'


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('newsletter:client_list')

    def form_valid(self, form):
        client = form.save()
        user = self.request.user
        client.user = user
        client.save()
        return super().form_valid(form)


class ClientDetailView(LoginRequiredMixin, UserIsOwnerOrHasPermissionMixin, DetailView):
    model = Client
    template_name = 'newsletter/client.html'

    def get(self, request, *args, **kwargs):
        if not self.test_func():
            return self.handle_no_permission()
        return super().get(request, *args, **kwargs)


class ClientUpdateView(LoginRequiredMixin, UserIsOwnerOrHasPermissionMixin, UpdateView):
    model = Client
    form_class = ClientForm
    permission_required = 'newsletter.update_client'
    template_name = 'newsletter/client_form.html'
    success_url = reverse_lazy('newsletter:client_list')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class ClientDeleteView(LoginRequiredMixin, UserIsOwnerOrHasPermissionMixin, DeleteView):
    model = Client
    permission_required = 'newsletter.delete_client'
    success_url = reverse_lazy('newsletter:client_list')

    def delete(self, request, *args, **kwargs):
        if not self.test_func():
            return self.handle_no_permission()
        return super().delete(request, *args, **kwargs)


# Message


class MessageListView(ListView):
    model = Message
    template_name = 'newsletter/message_list.html'


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('newsletter:message_list')

    def form_valid(self, form):
        message = form.save()
        user = self.request.user
        message.user = user
        message.save()
        return super().form_valid(form)


class MessageDetailView(LoginRequiredMixin, UserIsOwnerOrHasPermissionMixin, DetailView):
    model = Message
    template_name = 'newsletter/message.html'

    def get(self, request, *args, **kwargs):
        if not self.test_func():
            return self.handle_no_permission()
        return super().get(request, *args, **kwargs)


class MessageUpdateView(LoginRequiredMixin, UserIsOwnerOrHasPermissionMixin, UpdateView):
    model = Message
    form_class = MessageForm
    permission_required = 'newsletter.update_message'
    success_url = reverse_lazy('newsletter:message_list')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class MessageDeleteView(LoginRequiredMixin, UserIsOwnerOrHasPermissionMixin, DeleteView):
    model = Message
    permission_required = 'newsletter.delete_message'
    success_url = reverse_lazy('newsletter:message_list')

    def delete(self, request, *args, **kwargs):
        if not self.test_func():
            return self.handle_no_permission()
        return super().delete(request, *args, **kwargs)


class AttemptListView(ListView):
    model = Attempt
    template_name = 'newsletter/attempt_list.html'
    context_object_name = 'attempts'


class NewsletterFinishView(PermissionRequiredMixin, UpdateView):
    model = Newsletter
    form_class = NewsletterFinishForm
    template_name = 'newsletter/newsletter_finish_form.html'
    success_url = reverse_lazy('newsletter:newsletter_list')
    permission_required = 'newsletter.can_turn_the_newsletter_off'

newsletter/templates/newsletter/attempt_list.html
{% extends 'newsletter/base.html' %}

{% block content %}
<h2>Newsletter Sending Attempts</h2>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Newsletter</th>
            <th>Client</th>
            <th>Last Attempt Time</th>
            <th>Status</th>
            <th>Server Response</th>
        </tr>
    </thead>
    <tbody>
        {% for attempt in attempts %}
        <tr>
            <td>{{ attempt.newsletter.message }}</td>
            <td>{{ attempt.client }}</td>
            <td>{{ attempt.last_attempt_time }}</td>
            <td>{{ attempt.get_last_attempt_status_display }}</td>
            <td>{{ attempt.server_response }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

newsletter/templates/newsletter/client.html
{% extends 'newsletter/base.html' %}

{% block content %}
<div class="row text-center">
    <div class="col-8">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{ client.full_name }}</h4>
            </div>
            <div class="card-body">
                <h4 class="my-0 font-weight-normal">{{ client }}</h4> <br>
            </br>
                <h5 class="card-title pricing-card-title">{{ client.comment }}</h5>
                {% if user.is_authenticated and user == newsletter.user %}
                <a href="{% url 'newsletter:update_client' client.id %}" type="button"
                   class="btn btn-lg btn-block btn-outline-primary">Изменить</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

newsletter/templates/newsletter/client_confirm_delete.html
{% extends 'newsletter/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Вы уверены, что хотите удалить клиента "{{ object }}"?</p>
                        <button type="submit" class="btn  btn-success">Подтвердить</button>
                        <a href="{% url 'newsletter:client_list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

newsletter/templates/newsletter/client_list.html
{% extends 'newsletter/base.html' %}
{% load my_tags %}

{% block content %}
<div class="col-12 mb-5">
    {% if user.is_authenticated %}
    <h4 class="card-title pricing-card-title">Добавить:</h4>
    <a class="btn btn-outline-primary" href="{% url 'newsletter:create_newsletter' %}">Рассылку</a>
    <a class="btn btn-outline-primary" href="{% url 'newsletter:create_client' %}">Клиента</a>
    <a class="btn btn-outline-primary" href="{% url 'newsletter:create_message' %}">Сообщение</a>
    {% endif %}
</div>
{% for client in object_list %}
<div class="col-8">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <h4 class="my-0 font-weight-normal">{{ client.full_name }}</h4>
        </div>
        <div class="card-body">
            <h1 class="card-title pricing-card-title">{{ client }}</h1>
            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                <li style="text-align: center;">{{ client.comment|truncatechars:100 }}</li>
                {% for client in newsletter.clients.all %}
                <li style="text-align: center;">{{ client }}</li>
                {% endfor %}


            </ul>
            <div class="btn-group">
                {% if user.is_authenticated and user == client.user %}
                <a href="{% url 'newsletter:client_page' client.id %}" type="button"
                   class="btn btn-lg btn-block btn-outline-primary">Просмотреть</a>
                <a href="{% url 'newsletter:update_client' client.id %}" type="button"
                   class="btn btn-lg btn-block btn-outline-primary">Изменить</a>
                <a href="{% url 'newsletter:delete_client' client.id %}" type="button"
                   class="btn btn-lg btn-block btn-outline-primary">Удалить</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

newsletter/templates/newsletter/message_list.html
{% extends 'newsletter/base.html' %}
{% load my_tags %}

{% block content %}
<div class="col-12 mb-5">
    {% if user.is_authenticated %}
     <h4 class="card-title pricing-card-title">Добавить:</h4>
    <a class="btn btn-outline-primary" href="{% url 'newsletter:create_newsletter' %}">Рассылку</a>
    <a class="btn btn-outline-primary" href="{% url 'newsletter:create_client' %}">Клиента</a>
    <a class="btn btn-outline-primary" href="{% url 'newsletter:create_message' %}">Сообщение</a>
    {% endif %}
</div>
{% for message in object_list %}
<div class="col-8">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <h4 class="my-0 font-weight-normal">{{ message }}</h4>
        </div>
        <div class="card-body">
            <h5 class="card-title pricing-card-title">{{ message.content|truncatechars:100 }}</h5>
            {% for client in newsletter.clients.all %}
                <li style="text-align: center;">{{ client }}</li>
                {% endfor %}


            </ul>
            <div class="btn-group">
                {% if user.is_authenticated and user == message.user %}
                <a href="{% url 'newsletter:message_page' message.id %}" type="button"
                   class="btn btn-lg btn-block btn-outline-primary">Просмотреть</a>
                <a href="{% url 'newsletter:update_message' message.id %}" type="button"
                   class="btn btn-lg btn-block btn-outline-primary">Изменить</a>
                <a href="{% url 'newsletter:delete_message' message.id %}" type="button"
                   class="btn btn-lg btn-block btn-outline-primary">Удалить</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

newsletter/templates/newsletter/newsletter.html
{% extends 'newsletter/base.html' %}

{% block content %}
<div class="row text-center">
    <div class="col-8">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{ client }}</h4>
                <h4 class="my-0 font-weight-normal">{{ newsletter }}</h4>
            </div>
            <div class="card-body">
                <h1 class="card-title pricing-card-title">{{ object.message.topic }}</h1>
                <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                    <li style="text-align: center;">{{ object.message.content }}</li>
                    <br>
                    {% if user.is_authenticated and user == newsletter.user %}
                    {% for client in newsletter.clients.all %}
                    <li style="text-align: center;">{{ client }}</li>
                    {% endfor %}
                    {% endif %}
                    <li style="text-align: center;">
                    </li>
                </ul>
                <a href="{% url 'newsletter:update_newsletter' newsletter.id %}" type="button"
                   class="btn btn-lg btn-block btn-outline-primary">Изменить</a>
                {% if perms.newsletter.can_turn_the_newsletter_off %}
                {% if newsletter.finished %}
                <span class="btn btn-lg btn-block btn-outline-secondary">Завершено</span>
                {% else %}
                <a href="{% url 'newsletter:newsletter_finish' newsletter.id %}" type="button"
                   class="btn btn-lg btn-block btn-outline-danger">Завершить</a>
                {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

newsletter/templates/newsletter/newsletter_list.html
{% extends 'newsletter/base.html' %}
{% load my_tags %}

{% block content %}
<div class="col-12 mb-5">
    <div class="row">
        <div class="col-8">
            <div class="mb-4">
                <h2>Статистика</h2>
                <ul>
                    <li>Количество рассылок всего: {{ total_newsletters }}</li>
                    <li>Количество активных рассылок: {{ active_newsletters }}</li>
                    <li>Количество уникальных клиентов: {{ unique_clients }}</li>
                </ul>
            </div>
            {% if user.is_authenticated %}
            <h4 class="card-title pricing-card-title">Добавить:</h4>
            <a class="btn btn-outline-primary" href="{% url 'newsletter:create_newsletter' %}">Рассылку</a>
            <a class="btn btn-outline-primary" href="{% url 'newsletter:create_client' %}">Клиента</a>
            <a class="btn btn-outline-primary" href="{% url 'newsletter:create_message' %}">Сообщение</a>
            {% endif %}

            {% for newsletter in newsletters %}
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    {% if newsletter.end_date %}
                    <h4 class="my-0 font-weight-normal">{{ newsletter.initial }} - {{newsletter.end_date}}</h4>
                    {% else %}
                    <h4 class="my-0 font-weight-normal">{{ newsletter.initial }}</h4>
                    {% endif %}
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">{{ newsletter.message.topic }}</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li style="text-align: center;">{{ newsletter.message.content|truncatechars:100 }}</li>
                        <br>
                        {% if user.is_authenticated and user == newsletter.user %}
                        {% for client in newsletter.clients.all %}
                        <li style="text-align: center;">{{ client }}</li>
                        {% endfor %}
                        {% endif %}
                    </ul>
                    <div class="btn-group">
                        {% if user == newsletter.user or perms.newsletter.can_view_any_newsletter %}
                        <a href="{% url 'newsletter:newsletter_page' newsletter.id %}" type="button"
                           class="btn btn-lg btn-block btn-outline-primary">Просмотреть</a>
                        {% endif %}
                        {% if user == newsletter.user %}
                        <a href="{% url 'newsletter:update_newsletter' newsletter.id %}" type="button"
                           class="btn btn-lg btn-block btn-outline-primary">Изменить</a>
                        <a href="{% url 'newsletter:delete_newsletter' newsletter.id %}" type="button"
                           class="btn btn-lg btn-block btn-outline-primary">Удалить</a>
                        {% endif %}
                        {% if newsletter.finished %}
                        <span class="btn btn-lg btn-block btn-outline-secondary">Завершено</span>
                        {% else %}
                        <a href="{% url 'newsletter:newsletter_finish' newsletter.id %}" type="button"
                           class="btn btn-lg btn-block btn-outline-danger">Завершить</a>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="col-4">
            <h2>Случайные статьи</h2>
            {% for post in random_posts %}
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ post.title }}</h4>
                </div>
                <div class="card-body">
                    <p>{{ post.content|truncatewords:20 }}</p>
                    <img src="{{ post.preview.url }}" alt="{{ post.title }}" class="img-fluid">
                    <a href="{% url 'blog:post_detail' post.pk %}" class="btn btn-primary">Читать далее</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}