blog/urls.py
from django.urls import path

from blog.views import PostCreateView, PostListView, PostDetailView, PostDeleteView, PostUpdateView

app_name = 'blog'
# from blog.views import PostListView

urlpatterns = [
    path('', PostListView.as_view(), name='post_list'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from newsletter.views import ContactsTemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('contacts/', ContactsTemplateView.as_view(), name='contacts'),
    path('', include('newsletter.urls', namespace='newsletter')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import RegisterView, email_verification, UserResetPasswordView, UserListView, BlockUserView, \
    BlockUserConfirmView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='registration'),
    path('reset_password/', UserResetPasswordView.as_view(), name='reset_password'),
    path('email_confirmation/<str:token>/', email_verification, name='email_confirmation'),
    path('user_list/', UserListView.as_view(), name='user_list'),
    path('block_user/<int:pk>/', BlockUserView.as_view(), name='block_user'),
    path('block_user_confirm/<int:pk>/', BlockUserConfirmView.as_view(), name='block_user_confirm'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')

    phone = models.CharField(max_length=35, verbose_name='телефон', null=True, blank=True)
    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', null=True, blank=True)
    country = models.CharField(max_length=40, verbose_name='страна')

    token = models.CharField(max_length=100, verbose_name='token', null=True, blank=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'
        permissions = [
            (
                'can_see_all_the_users',
                'can_see_all_the_users'
            ),
            (
                'can_block_users',
                'can_block_users'
            ),

        ]

    def __str__(self):
        return self.email

users/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.utils.translation import gettext_lazy as _

from newsletter.forms import FormStyleMixin
from users.models import User


class UserRegisterForm(FormStyleMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')
    password1 = forms.CharField(
        label=_("Пароль"),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label=_("Подтверждение пароля"),
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        strip=False,
        help_text=_("Повторно введите выбранный пароль"),
    )


class RecoveryForm(forms.Form, FormStyleMixin):
    email = forms.EmailField(label="Email")

users/views.py
import random
import secrets
import string
from django.contrib.auth.hashers import make_password
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.views import PasswordResetView
from django.core.mail import send_mail
from django.http import HttpResponseRedirect, request
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, View, TemplateView
from django.contrib import messages
from config.settings import EMAIL_HOST_USER, DEFAULT_FROM_EMAIL
from users.forms import UserRegisterForm, RecoveryForm
from users.models import User


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f'http://{host}/users/email_confirmation/{token}/'
        send_mail(
            subject='Подтверждение почты',
            message=f'Перейдите по ссылке для подтверждения почты {url}',
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email]
        )
        return super().form_valid(form)


def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse('users:login'))


class UserResetPasswordView(PasswordResetView):
    form_class = RecoveryForm
    template_name = 'users/reset_password.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        email = form.cleaned_data['email']
        user_exists = User.objects.filter(email=email).exists()
        if user_exists:
            user = User.objects.get(email=email)
            character = string.ascii_letters + string.digits
            password = "".join(secrets.choice(character) for i in range(12))
            user.set_password(password)
            user.save()
            send_mail(
                subject="Восстановление пароля",
                message=f"Ваш пароль от сайта News.com изменен:\n"
                        f"Email: {email}\n"
                        f"Пароль: {password}",
                from_email=DEFAULT_FROM_EMAIL,
                recipient_list=[user.email]
            )
            return HttpResponseRedirect(self.get_success_url())
        else:
            return HttpResponseRedirect(reverse('users:registration'))


class UserListView(PermissionRequiredMixin, ListView):
    model = User
    template_name = 'users/user_list.html'
    context_object_name = 'users'
    permission_required = 'users.can_see_all_the_users'

    def get_queryset(self):
        return User.objects.all()


class BlockUserConfirmView(PermissionRequiredMixin, TemplateView):
    template_name = 'users/block_user_confirm.html'
    permission_required = 'users.can_block_users'
    success_url = reverse_lazy('users:user_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = get_object_or_404(User, pk=kwargs['pk'])
        context['user_to_block'] = user
        return context

    def post(self, request, *args, **kwargs):
        user = get_object_or_404(User, pk=kwargs['pk'])
        user.is_active = False
        user.save()
        messages.success(request, f'User {user.email} has been blocked.')
        return redirect('users:user_list')


class BlockUserView(PermissionRequiredMixin, View):
    permission_required = 'users.can_block_users'

    def post(self, request, pk):
        user = get_object_or_404(User, pk=pk)
        user.is_active = False
        user.save()
        messages.success(request, f'User {user.email} has been blocked.')
        return redirect('users:user_list')

users/templates/users/block_user_confirm.html
{% extends 'newsletter/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Заблокировать пользователя {{ user.email }}?</p>
                        <button type="submit" class="btn  btn-danger">Подтвердить</button>
                        <a href="{% url 'users:user_list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/login.html
{% extends 'newsletter/base.html' %}

{% block content %}
<div class="container">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Вход
                    </h3>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                    <button type="submit" class="btn btn-success">
                        Войти
                    </button>
                    <a class="btn btn-outline-primary" href="{% url 'users:registration' %}">Регистрация</a>
                    <a class="btn btn-outline-primary" href="{% url 'users:reset_password' %}">Забыли пароль?</a>
                </div>
            </div>
        </div>
</div>
</div>
</form>
</div>


{% endblock %}

users/templates/users/register.html
{% extends 'newsletter/base.html' %}

{% block content %}
<div class="container">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Регистрация
                    </h3>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                    <button type="submit" class="btn btn-success">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Зарегистрироваться
                        {% endif %}
                    </button>
                </div>
            </div>
        </div>
</div>
</div>
</form>
</div>


{% endblock %}

users/templates/users/reset_password.html
{% extends 'newsletter/base.html' %}

{% block content %}
<div class="container">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Восстановление пароля
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-outline-success">
                        Восстановить пароль
                    </button>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/user_list.html
{% extends "newsletter/base.html" %}

{% block content %}
<h2>User List</h2>
<table>
    <thead>
    <tr>
        <th>Email</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    {% for user in users %}
    <tr>
        <td>{{ user.email }}</td>
        <td>
            {% if user.is_active %}
            <a class="btn btn-danger" href="{% url 'users:block_user_confirm' user.id %}">Block</a>
            {% else %}
            Blocked
            {% endif %}
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}